name: Tidy documentation
title: null
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme 
titles_from_headings:
  enabled: true
  strip_title: true
  collections: true 
header_pages:
  - explore.md
  - login.md
  - registration.md
  - profile.md
  - project.md
  - planner.md
  - todo.md
  - issues.md
  - files.md
  - calendar.md
