name: Tidy documentation
title: null
theme: minima
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
header_pages:
  - user-documentation/explore.md
  - user-documentation/login.md
  - user-documentation/registration.md
  - user-documentation/profile.md
  - user-documentation/project.md
  - user-documentation/planner.md
  - user-documentation/todo.md
  - user-documentation/issues.md
  - user-documentation/files.md
  - user-documentation/calendar.md
